project:
  output-dir: output

number-sections: true
bibliography: references.bib
link-citations: true
execute:
  freeze: auto

format:
  html:
    toc: true
    toc-location: left
    theme:
      light:
        - ./custom.scss
        dark:
        - ./custom.scss
        - ./custom-dark.scss
  pdf:
    margin-left: 20mm
    margin-top: 30mm
    margin-right: 20mm
    margin-bottom: 30mm
